# https://circleci.com/developer/orbs/orb/circleci/terraform
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
  environment:
    TF_IN_AUTOMATION: "true"

jobs:
  plan-apply:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - terraform-{{ checksum ".terraform.lock.hcl" }}
            - terraform-
      - run:
          name: terraform init & plan
          command: |
            terraform init -input=false
            terraform plan -out tfapply -var-file variables.tfvars
      - store_artifacts:
          path: .terraform.lock.hcl
      - save_cache:
          key: terraform-{{ checksum ".terraform.lock.hcl" }}
          paths:
            - .terraform
      - persist_to_workspace:
          root: ~/repo
          paths:
            - "*.tf"
            - "*.tfvars"
            - "*.hcl"
            - "tfapply"

  apply:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: terraform
          command: |
            terraform apply -auto-approve tfapply
      - restore_cache:
          keys:
            - terraform-{{ checksum ".terraform.lock.hcl" }}
            - terraform-

  plan-destroy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: terraform create destroy plan
          command: |
            terraform plan -destroy -out tfdestroy -var-file variables.tfvars
      - restore_cache:
          keys:
            - terraform-{{ checksum ".terraform.lock.hcl" }}
            - terraform-
      - persist_to_workspace:
          root: ~/repo
          paths:
            - "tfdestroy"

  destroy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: terraform destroy
          command: |
            terraform apply -auto-approve tfdestroy
      - restore_cache:
          keys:
            - terraform-{{ checksum ".terraform.lock.hcl" }}
            - terraform-

workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - plan-apply
      - hold-apply:
          type: approval
          requires:
            - plan-apply
      - apply:
          requires:
            - hold-apply
      - plan-destroy:
          requires:
            - apply
      - hold-destroy:
          type: approval
          requires:
            - plan-destroy
      - destroy:
          requires:
            - hold-destroy
